// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrKEQVmaqyYftcnCXtu_N4JGNC2XE4DYg',
    appId: '1:133233248323:web:379954ec38c6cb90c1ecf6',
    messagingSenderId: '133233248323',
    projectId: 'iot-firebase-de1ed',
    authDomain: 'iot-firebase-de1ed.firebaseapp.com',
    storageBucket: 'iot-firebase-de1ed.firebasestorage.app',
    measurementId: 'G-PCERT8H0KG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXAlmTwY7yOc05MKtjB8g_bHpIwU0F_v4',
    appId: '1:133233248323:android:354d45593fc83c03c1ecf6',
    messagingSenderId: '133233248323',
    projectId: 'iot-firebase-de1ed',
    storageBucket: 'iot-firebase-de1ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9cIK-ZiNt1Sr7DI9XizcSuSUJGwYmbsk',
    appId: '1:133233248323:ios:52e9471b239eeecdc1ecf6',
    messagingSenderId: '133233248323',
    projectId: 'iot-firebase-de1ed',
    storageBucket: 'iot-firebase-de1ed.firebasestorage.app',
    iosBundleId: 'com.example.firebaseproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9cIK-ZiNt1Sr7DI9XizcSuSUJGwYmbsk',
    appId: '1:133233248323:ios:52e9471b239eeecdc1ecf6',
    messagingSenderId: '133233248323',
    projectId: 'iot-firebase-de1ed',
    storageBucket: 'iot-firebase-de1ed.firebasestorage.app',
    iosBundleId: 'com.example.firebaseproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrKEQVmaqyYftcnCXtu_N4JGNC2XE4DYg',
    appId: '1:133233248323:web:a66116fd55d8d411c1ecf6',
    messagingSenderId: '133233248323',
    projectId: 'iot-firebase-de1ed',
    authDomain: 'iot-firebase-de1ed.firebaseapp.com',
    storageBucket: 'iot-firebase-de1ed.firebasestorage.app',
    measurementId: 'G-XD2SGF5NNC',
  );
}
